using Newtonsoft.Json;
using System.Collections.Generic;

/// <summary>
/// Represents the LMMInferenceResponse schema.
/// </summary>
public class LMMInferenceResponse
{
    /// <summary>
    /// Unique identifier of inference
    /// </summary>
    [JsonProperty("inference_id")] 
    public string Inference_Id { get; set; }

    /// <summary>
    /// The frame id of the image used in inference if the input was a video
    /// </summary>
    [JsonProperty("frame_id")] 
    public int? Frame_Id { get; set; }

    /// <summary>
    /// The time in seconds it took to produce the predictions including image preprocessing
    /// </summary>
    [JsonProperty("time")] 
    public float? Time { get; set; }

    /// <summary>
    /// Gets or sets the image.
    /// </summary>
    [JsonProperty("image")] 
    [JsonConverter(typeof(SingleOrArrayConverter<InferenceResponseImage>))]
    public List<InferenceResponseImage> Image { get; set; }

    /// <summary>
    /// Text/structured response generated by model
    /// </summary>
    [JsonProperty("response")] 
    public object Response { get; set; }

    /// <summary>
    /// Initializes a new instance of <see cref="LMMInferenceResponse"/>.
    /// </summary>
    /// <param name="image">The image.</param>
    /// <param name="response">The response.</param>
    public LMMInferenceResponse(List<InferenceResponseImage> image, object response)
    {
        this.Image = image;
        this.Response = response;
    }
}